
    export let dogs = [
      {
        id: 1,
        name: 'Affenpinscher',
        height: '23 - 29',
        weight: '3 - 6',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/BJa4kxc4X.jpg',
        temperament: 'Stubborn, Curious, Playful, Adventurous, Active, Fun-loving',
        createdInDatabase: false
      },
      {
        id: 2,
        name: 'Afghan Hound',
        height: '64 - 69',
        weight: '23 - 27',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/hMyT4CDXR.jpg',
        temperament: 'Aloof, Clownish, Dignified, Independent, Happy',
        createdInDatabase: false
      },
      {
        id: 3,
        name: 'African Hunting Dog',
        height: '76',
        weight: '20 - 30',
        life_span: '11 years',
        image: 'https://cdn2.thedogapi.com/images/rkiByec47.jpg',
        temperament: 'Wild, Hardworking, Dutiful',
        createdInDatabase: false
      },
      {
        id: 4,
        name: 'Airedale Terrier',
        height: '53 - 58',
        weight: '18 - 29',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/1-7cgoZSh.jpg',
        temperament: 'Outgoing, Friendly, Alert, Confident, Intelligent, Courageous',
        createdInDatabase: false
      },
      {
        id: 5,
        name: 'Akbash Dog',
        height: '71 - 86',
        weight: '41 - 54',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/26pHT3Qk7.jpg',
        temperament: 'Loyal, Independent, Intelligent, Brave',
        createdInDatabase: false
      },
      {
        id: 6,
        name: 'Akita',
        height: '61 - 71',
        weight: '29 - 52',
        life_span: '10 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/BFRYBufpm.jpg',
        temperament: 'Docile, Alert, Responsive, Dignified, Composed, Friendly, Receptive, Faithful, Courageous',
        createdInDatabase: false
      },
      {
        id: 7,
        name: 'Alapaha Blue Blood Bulldog',
        height: '46 - 61',
        weight: '25 - 41',
        life_span: '12 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/33mJ-V3RX.jpg',
        temperament: 'Loving, Protective, Trainable, Dutiful, Responsible',
        createdInDatabase: false
      },
      {
        id: 8,
        name: 'Alaskan Husky',
        height: '58 - 66',
        weight: '17 - 23',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/-HgpNnGXl.jpg',
        temperament: 'Friendly, Energetic, Loyal, Gentle, Confident',
        createdInDatabase: false
      },
      {
        id: 9,
        name: 'Alaskan Malamute',
        height: '58 - 64',
        weight: '29 - 45',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/dW5UucTIW.jpg',
        temperament: 'Friendly, Affectionate, Devoted, Loyal, Dignified, Playful',
        createdInDatabase: false
      },
      {
        id: 10,
        name: 'American Bulldog',
        height: '56 - 69',
        weight: '27 - 54',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/pk1AAdloG.jpg',
        temperament: 'Friendly, Assertive, Energetic, Loyal, Gentle, Confident, Dominant',
        createdInDatabase: false
      },
      {
        id: 11,
        name: 'American Bully',
        height: '36 - 43',
        weight: '14 - 68',
        life_span: '8 – 15 years',
        image: 'https://cdn2.thedogapi.com/images/sqQJDtbpY.jpg',
        temperament: 'Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous',
        createdInDatabase: false
      },
      {
        id: 12,
        name: 'American Eskimo Dog',
        height: '38 - 48',
        weight: '9 - 18',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/Bymjyec4m.jpg',
        temperament: 'Friendly, Alert, Reserved, Intelligent, Protective',
        createdInDatabase: false
      },
      {
        id: 13,
        name: 'American Eskimo Dog (Miniature)',
        height: '23 - 30',
        weight: '3 - 5',
        life_span: '13 – 15 years',
        image: 'https://cdn2.thedogapi.com/images/_gn8GLrE6.jpg',
        temperament: 'Friendly, Alert, Reserved, Intelligent, Protective',
        createdInDatabase: false
      },
      {
        id: 14,
        name: 'American Foxhound',
        height: '53 - 71',
        weight: '29 - 34',
        life_span: '8 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/S14n1x9NQ.jpg',
        temperament: 'Kind, Sweet-Tempered, Loyal, Independent, Intelligent, Loving',
        createdInDatabase: false
      },
      {
        id: 15,
        name: 'American Pit Bull Terrier',
        height: '43 - 53',
        weight: '14 - 27',
        life_span: '10 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/HkC31gcNm.png',
        temperament: 'Strong Willed, Stubborn, Friendly, Clownish, Affectionate, Loyal, Obedient, Intelligent, Courageous',
        createdInDatabase: false
      },
      {
        id: 16,
        name: 'American Staffordshire Terrier',
        height: '43 - 48',
        weight: '23 - 27',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/rJIakgc4m.jpg',
        temperament: 'Tenacious, Friendly, Devoted, Loyal, Attentive, Courageous',
        createdInDatabase: false
      },
      {
        id: 17,
        name: 'American Water Spaniel',
        height: '38 - 46',
        weight: '11 - 20',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/SkmRJl9VQ.jpg',
        temperament: 'Friendly, Energetic, Obedient, Intelligent, Protective, Trainable',
        createdInDatabase: false
      },
      {
        id: 18,
        name: 'Anatolian Shepherd Dog',
        height: '69 - 74',
        weight: '36 - 68',
        life_span: '11 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/BJT0Jx5Nm.jpg',
        temperament: 'Steady, Bold, Independent, Confident, Intelligent, Proud',
        createdInDatabase: false
      },
      {
        id: 19,
        name: 'Appenzeller Sennenhund',
        height: '51 - 56',
        weight: '22 - 25',
        life_span: '12 – 14 years',
        image: 'https://cdn2.thedogapi.com/images/HkNkxlqEX.jpg',
        temperament: 'Reliable, Fearless, Energetic, Lively, Self-assured',
        createdInDatabase: false
      },
      {
        id: 21,
        name: 'Australian Cattle Dog',
        height: '43 - 51',
        weight: '20 - 28',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/IBkYVm4v1.jpg',
        temperament: 'Cautious, Energetic, Loyal, Obedient, Protective, Brave',
        createdInDatabase: false
      },
      {
        id: 22,
        name: 'Australian Kelpie',
        height: '43 - 51',
        weight: '14 - 21',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/Hyq1ge9VQ.jpg',
        temperament: 'Friendly, Energetic, Alert, Loyal, Intelligent, Eager',
        createdInDatabase: false
      },
      {
        id: 23,
        name: 'Australian Shepherd',
        height: '46 - 58',
        weight: '16 - 29',
        life_span: '12 - 16 years',
        image: 'https://cdn2.thedogapi.com/images/B1-llgq4m.jpg',
        temperament: 'Good-natured, Affectionate, Intelligent, Active, Protective',
        createdInDatabase: false
      },
      {
        id: 24,
        name: 'Australian Terrier',
        height: '25 - 28',
        weight: '6 - 7',
        life_span: '15 years',
        image: 'https://cdn2.thedogapi.com/images/r1Ylge5Vm.jpg',
        temperament: 'Spirited, Alert, Loyal, Companionable, Even Tempered, Courageous',
        createdInDatabase: false
      },
      {
        id: 25,
        name: 'Azawakh',
        height: '58 - 74',
        weight: '15 - 25',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/SkvZgx94m.jpg',
        temperament: 'Aloof, Affectionate, Attentive, Rugged, Fierce, Refined',
        createdInDatabase: false
      },
      {
        id: 26,
        name: 'Barbet',
        height: '51 - 66',
        weight: '18 - 29',
        life_span: '13 – 15 years',
        image: 'https://cdn2.thedogapi.com/images/HyWGexcVQ.jpg',
        temperament: 'Obedient, Companionable, Intelligent, Joyful',
        createdInDatabase: false
      },
      {
        id: 28,
        name: 'Basenji',
        height: '41 - 43',
        weight: '10 - 11',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/H1dGlxqNQ.jpg',
        temperament: 'Affectionate, Energetic, Alert, Curious, Playful, Intelligent',
        createdInDatabase: false
      },
      {
        id: 29,
        name: 'Basset Bleu de Gascogne',
        height: '33 - 38',
        weight: '16 - 18',
        life_span: '10 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/BkMQll94X.jpg',
        temperament: 'Affectionate, Lively, Agile, Curious, Happy, Active',
        createdInDatabase: false
      },
      {
        id: 30,
        name: 'Basset Hound',
        height: '36',
        weight: '23 - 29',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/Sy57xx9EX.jpg',
        temperament: 'Tenacious, Friendly, Affectionate, Devoted, Sweet-Tempered, Gentle',
        createdInDatabase: false
      },
      {
        id: 31,
        name: 'Beagle',
        height: '33 - 38',
        weight: '9 - 16',
        life_span: '13 - 16 years',
        image: 'https://cdn2.thedogapi.com/images/Syd4xxqEm.jpg',
        temperament: 'Amiable, Even Tempered, Excitable, Determined, Gentle, Intelligent',
        createdInDatabase: false
      },
      {
        id: 32,
        name: 'Bearded Collie',
        height: '51 - 56',
        weight: '20 - 25',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/A09F4c1qP.jpg',
        temperament: 'Self-confidence, Hardy, Lively, Alert, Intelligent, Active',
        createdInDatabase: false
      },
      {
        id: 33,
        name: 'Beauceron',
        height: '61 - 70',
        weight: '36 - 50',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/HJQ8ge5V7.jpg',
        temperament: 'Fearless, Friendly, Intelligent, Protective, Calm',
        createdInDatabase: false
      },
      {
        id: 34,
        name: 'Bedlington Terrier',
        height: '38 - 41',
        weight: '8 - 10',
        life_span: '14 - 16 years',
        image: 'https://cdn2.thedogapi.com/images/ByK8gx947.jpg',
        temperament: 'Affectionate, Spirited, Intelligent, Good-tempered',
        createdInDatabase: false
      },
      {
        id: 36,
        name: 'Belgian Malinois',
        height: '56 - 66',
        weight: '18 - 36',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/r1f_ll5VX.jpg',
        temperament: 'Watchful, Alert, Stubborn, Friendly, Confident, Hard-working, Active, Protective',
        createdInDatabase: false
      },
      {
        id: 38,
        name: 'Belgian Tervuren',
        height: '56 - 66',
        weight: '18 - 29',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/B1KdxlcNX.jpg',
        temperament: 'Energetic, Alert, Loyal, Intelligent, Attentive, Protective',
        createdInDatabase: false
      },
      {
        id: 41,
        name: 'Bernese Mountain Dog',
        height: '58 - 70',
        weight: '29 - 54',
        life_span: '7 - 10 years',
        image: 'https://cdn2.thedogapi.com/images/S1fFlx5Em.jpg',
        temperament: 'Affectionate, Loyal, Intelligent, Faithful',
        createdInDatabase: false
      },
      {
        id: 42,
        name: 'Bichon Frise',
        height: '24 - 29',
        weight: '5 - 8',
        life_span: '15 years',
        image: 'https://cdn2.thedogapi.com/images/HkuYlxqEQ.jpg',
        temperament: 'Feisty, Affectionate, Cheerful, Playful, Gentle, Sensitive',
        createdInDatabase: false
      },
      {
        id: 43,
        name: 'Black and Tan Coonhound',
        height: '58 - 69',
        weight: '29 - 45',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/HJAFgxcNQ.jpg',
        temperament: 'Easygoing, Gentle, Adaptable, Trusting, Even Tempered, Lovable',
        createdInDatabase: false
      },
      {
        id: 45,
        name: 'Bloodhound',
        height: '58 - 69',
        weight: '36 - 50',
        life_span: '8 - 10 years',
        image: 'https://cdn2.thedogapi.com/images/Skdcgx9VX.jpg',
        temperament: 'Stubborn, Affectionate, Gentle, Even Tempered',
        createdInDatabase: false
      },
      {
        id: 47,
        name: 'Bluetick Coonhound',
        height: '53 - 69',
        weight: '20 - 36',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/rJxieg9VQ.jpg',
        temperament: 'Friendly, Intelligent, Active',
        createdInDatabase: false
      },
      {
        id: 48,
        name: 'Boerboel',
        height: '56 - 69',
        weight: '50 - 91',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/HyOjge5Vm.jpg',
        temperament: 'Obedient, Confident, Intelligent, Dominant, Territorial',
        createdInDatabase: false
      },
      {
        id: 50,
        name: 'Border Collie',
        height: '46 - 56',
        weight: '14 - 20',
        life_span: '12 - 16 years',
        image: 'https://cdn2.thedogapi.com/images/sGQvQUpsp.jpg',
        temperament: 'Tenacious, Keen, Energetic, Responsive, Alert, Intelligent',
        createdInDatabase: false
      },
      {
        id: 51,
        name: 'Border Terrier',
        height: '28 - 41',
        weight: '5 - 7',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/HJOpge9Em.jpg',
        temperament: 'Fearless, Affectionate, Alert, Obedient, Intelligent, Even Tempered',
        createdInDatabase: false
      },
      {
        id: 53,
        name: 'Boston Terrier',
        height: '41 - 43',
        weight: '5 - 11',
        life_span: '11 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/rkZRggqVX.jpg',
        temperament: 'Friendly, Lively, Intelligent',
        createdInDatabase: false
      },
      {
        id: 54,
        name: 'Bouvier des Flandres',
        height: '60 - 70',
        weight: '32 - 50',
        life_span: '10 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/Byd0xl5VX.jpg',
        temperament: 'Protective, Loyal, Gentle, Intelligent, Familial, Rational',
        createdInDatabase: false
      },
      {
        id: 55,
        name: 'Boxer',
        height: '55 - 64',
        weight: '23 - 32',
        life_span: '8 - 10 years',
        image: 'https://cdn2.thedogapi.com/images/ry1kWe5VQ.jpg',
        temperament: 'Devoted, Fearless, Friendly, Cheerful, Energetic, Loyal, Playful, Confident, Intelligent, Bright, Brave, Calm',
        createdInDatabase: false
      },
      {
        id: 56,
        name: 'Boykin Spaniel',
        height: '36 - 46',
        weight: '11 - 18',
        life_span: '10 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/ryHJZlcNX.jpg',
        temperament: 'Friendly, Energetic, Companionable, Intelligent, Eager, Trainable',
        createdInDatabase: false
      },
      {
        id: 57,
        name: 'Bracco Italiano',
        height: '55 - 67',
        weight: '25 - 40',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/S13yZg5VQ.jpg',
        temperament: 'Stubborn, Affectionate, Loyal, Playful, Companionable, Trainable',
        createdInDatabase: false
      },
      {
        id: 58,
        name: 'Briard',
        height: '56 - 69',
        weight: '32 - 41',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/rkVlblcEQ.jpg',
        temperament: 'Fearless, Loyal, Obedient, Intelligent, Faithful, Protective',
        createdInDatabase: false
      },
      {
        id: 59,
        name: 'Brittany',
        height: '44 - 52',
        weight: '14 - 20',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/HJWZZxc4X.jpg',
        temperament: 'Agile, Adaptable, Quick, Intelligent, Attentive, Happy',
        createdInDatabase: false
      },
      {
        id: 61,
        name: 'Bull Terrier',
        height: '53 - 56',
        weight: '23 - 32',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/VSraIEQGd.jpg',
        temperament: 'Trainable, Protective, Sweet-Tempered, Keen, Active',
        createdInDatabase: false
      },
      {
        id: 62,
        name: 'Bull Terrier (Miniature)',
        height: '25 - 36',
        weight: '11 - 15',
        life_span: '11 – 14 years',
        image: 'https://cdn2.thedogapi.com/images/BkKZWlcVX.jpg',
        temperament: 'Trainable, Protective, Sweet-Tempered, Keen, Active, Territorial',
        createdInDatabase: false
      },
      {
        id: 64,
        name: 'Bullmastiff',
        height: '61 - 69',
        weight: '45 - 59',
        life_span: '8 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/r1ifZl5E7.jpg',
        temperament: 'Docile, Reliable, Devoted, Alert, Loyal, Reserved, Loving, Protective, Powerful, Calm, Courageous',
        createdInDatabase: false
      },
      {
        id: 65,
        name: 'Cairn Terrier',
        height: '23 - 25',
        weight: '6 - 6',
        life_span: '14 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/Sk7Qbg9E7.jpg',
        temperament: 'Hardy, Fearless, Assertive, Gay, Intelligent, Active',
        createdInDatabase: false
      },
      {
        id: 67,
        name: 'Cane Corso',
        height: '60 - 70',
        weight: '40 - 54',
        life_span: '10 - 11 years',
        image: 'https://cdn2.thedogapi.com/images/r15m-lc4m.jpg',
        temperament: 'Trainable, Reserved, Stable, Quiet, Even Tempered, Calm',
        createdInDatabase: false
      },
      {
        id: 68,
        name: 'Cardigan Welsh Corgi',
        height: '27 - 32',
        weight: '11 - 17',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/SyXN-e9NX.jpg',
        temperament: 'Affectionate, Devoted, Alert, Companionable, Intelligent, Active',
        createdInDatabase: false
      },
      {
        id: 69,
        name: 'Catahoula Leopard Dog',
        height: '51 - 66',
        weight: '23 - 43',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/BJcNbec4X.jpg',
        temperament: 'Energetic, Inquisitive, Independent, Gentle, Intelligent, Loving',
        createdInDatabase: false
      },
      {
        id: 70,
        name: 'Caucasian Shepherd (Ovcharka)',
        height: '61 - 85',
        weight: '36 - 45',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/r1rrWe5Em.jpg',
        temperament: 'Alert, Quick, Dominant, Powerful, Calm, Strong',
        createdInDatabase: false
      },
      {
        id: 71,
        name: 'Cavalier King Charles Spaniel',
        height: '30 - 33',
        weight: '6 - 8',
        life_span: '10 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/HJRBbe94Q.jpg',
        temperament: 'Fearless, Affectionate, Sociable, Patient, Playful, Adaptable',
        createdInDatabase: false
      },
      {
        id: 76,
        name: 'Chesapeake Bay Retriever',
        height: '53 - 66',
        weight: '25 - 36',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/9BXwUeCc2.jpg',
        temperament: 'Affectionate, Intelligent, Quiet, Dominant, Happy, Protective',
        createdInDatabase: false
      },
      {
        id: 78,
        name: 'Chinese Crested',
        height: '28 - 33',
        weight: '5 - 6',
        life_span: '10 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/B1pDZx9Nm.jpg',
        temperament: 'Affectionate, Sweet-Tempered, Lively, Alert, Playful, Happy',
        createdInDatabase: false
      },
      {
        id: 79,
        name: 'Chinese Shar-Pei',
        height: '46 - 51',
        weight: '20 - 27',
        life_span: '10 years',
        image: 'https://cdn2.thedogapi.com/images/B1ruWl94Q.jpg',
        temperament: 'Suspicious, Affectionate, Devoted, Reserved, Independent, Loving',
        createdInDatabase: false
      },
      {
        id: 80,
        name: 'Chinook',
        height: '56 - 66',
        weight: '23 - 41',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/Sypubg54Q.jpg',
        temperament: 'Friendly, Alert, Dignified, Intelligent, Calm',
        createdInDatabase: false
      },
      {
        id: 81,
        name: 'Chow Chow',
        height: '43 - 51',
        weight: '18 - 32',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/ry8KWgqEQ.jpg',
        temperament: 'Aloof, Loyal, Independent, Quiet',
        createdInDatabase: false
      },
      {
        id: 84,
        name: 'Clumber Spaniel',
        height: '43 - 51',
        weight: '25 - 39',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/rkeqWgq4Q.jpg',
        temperament: 'Affectionate, Loyal, Dignified, Gentle, Calm, Great-hearted',
        createdInDatabase: false
      },
      {
        id: 86,
        name: 'Cocker Spaniel',
        height: '36 - 38',
        weight: '9 - 14',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/1lFmrzECl.jpg',
        temperament: 'Trainable, Friendly, Affectionate, Playful, Quiet, Faithful',
        createdInDatabase: false
      },
      {
        id: 87,
        name: 'Cocker Spaniel (American)',
        height: '36 - 38',
        weight: '9 - 14',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/HkRcZe547.jpg',
        temperament: 'Outgoing, Sociable, Trusting, Joyful, Even Tempered, Merry',
        createdInDatabase: false
      },
      {
        id: 89,
        name: 'Coton de Tulear',
        height: '23 - 28',
        weight: '4 - 7',
        life_span: '13 - 16 years',
        image: 'https://cdn2.thedogapi.com/images/SyviZlqNm.jpg',
        temperament: 'Affectionate, Lively, Playful, Intelligent, Trainable, Vocal',
        createdInDatabase: false
      },
      {
        id: 92,
        name: 'Dalmatian',
        height: '48 - 58',
        weight: '23 - 25',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/SkJ3blcN7.jpg',
        temperament: 'Outgoing, Friendly, Energetic, Playful, Sensitive, Intelligent, Active',
        createdInDatabase: false
      },
      {
        id: 94,
        name: 'Doberman Pinscher',
        height: '61 - 71',
        weight: '30 - 40',
        life_span: '10 years',
        image: 'https://cdn2.thedogapi.com/images/HyL3bl94Q.jpg',
        temperament: 'Fearless, Energetic, Alert, Loyal, Obedient, Confident, Intelligent',
        createdInDatabase: false
      },
      {
        id: 95,
        name: 'Dogo Argentino',
        height: '60 - 69',
        weight: '36 - 45',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/S1nhWx94Q.jpg',
        temperament: 'Friendly, Affectionate, Cheerful, Loyal, Tolerant, Protective',
        createdInDatabase: false
      },
      {
        id: 98,
        name: 'Dutch Shepherd',
        height: '56 - 62',
        weight: '23 - 32',
        life_span: '15 years',
        image: 'https://cdn2.thedogapi.com/images/BkE6Wg5E7.jpg',
        temperament: 'Reliable, Affectionate, Alert, Loyal, Obedient, Trainable',
        createdInDatabase: false
      },
      {
        id: 101,
        name: 'English Setter',
        height: '61 - 64',
        weight: '20 - 36',
        life_span: '12 years',
        image: 'https://cdn2.thedogapi.com/images/By4A-eqVX.jpg',
        temperament: 'Strong Willed, Mischievous, Affectionate, Energetic, Playful, Companionable, Gentle, Hard-working, Intelligent, Eager, People-Oriented',
        createdInDatabase: false
      },
      {
        id: 102,
        name: 'English Shepherd',
        height: '46 - 58',
        weight: '20 - 30',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/H1QyMe5EQ.jpg',
        temperament: 'Kind, Energetic, Independent, Adaptable, Intelligent, Bossy',
        createdInDatabase: false
      },
      {
        id: 103,
        name: 'English Springer Spaniel',
        height: '48 - 51',
        weight: '16 - 23',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/Hk0Jfe5VQ.jpg',
        temperament: 'Affectionate, Cheerful, Alert, Intelligent, Attentive, Active',
        createdInDatabase: false
      },
      {
        id: 104,
        name: 'English Toy Spaniel',
        height: '25',
        weight: '4 - 6',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/SkIgzxqNQ.jpg',
        temperament: 'Affectionate, Reserved, Playful, Gentle, Happy, Loving',
        createdInDatabase: false
      },
      {
        id: 105,
        name: 'English Toy Terrier',
        height: '25 - 30',
        weight: '3 - 4',
        life_span: '12 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/SJ6eMxqEQ.jpg',
        temperament: 'Stubborn, Alert, Companionable, Intelligent, Cunning, Trainable',
        createdInDatabase: false
      },
      {
        id: 107,
        name: 'Eurasier',
        height: '52 - 60',
        weight: '18 - 32',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/S1VWGx9Nm.jpg',
        temperament: 'Alert, Reserved, Intelligent, Even Tempered, Watchful, Calm',
        createdInDatabase: false
      },
      {
        id: 108,
        name: 'Field Spaniel',
        height: '43 - 46',
        weight: '16 - 23',
        life_span: '11 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/SkJfGecE7.jpg',
        temperament: 'Docile, Cautious, Sociable, Sensitive, Adaptable, Familial',
        createdInDatabase: false
      },
      {
        id: 110,
        name: 'Finnish Lapphund',
        height: '41 - 53',
        weight: '15 - 24',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/S1KMGg5Vm.jpg',
        temperament: 'Friendly, Keen, Faithful, Calm, Courageous',
        createdInDatabase: false
      },
      {
        id: 111,
        name: 'Finnish Spitz',
        height: '39 - 51',
        weight: '10 - 13',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/3PjHlQbkV.jpg',
        temperament: 'Playful, Loyal, Independent, Intelligent, Happy, Vocal',
        createdInDatabase: false
      },
      {
        id: 113,
        name: 'French Bulldog',
        height: '28 - 30',
        weight: '13',
        life_span: '9 - 11 years',
        image: 'https://cdn2.thedogapi.com/images/HyWNfxc47.jpg',
        temperament: 'Playful, Affectionate, Keen, Sociable, Lively, Alert, Easygoing, Patient, Athletic, Bright',
        createdInDatabase: false
      },
      {
        id: 114,
        name: 'German Pinscher',
        height: '43 - 51',
        weight: '11 - 20',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/B1u4zgqE7.jpg',
        temperament: 'Spirited, Lively, Intelligent, Loving, Even Tempered, Familial',
        createdInDatabase: false
      },
      {
        id: 115,
        name: 'German Shepherd Dog',
        height: '56 - 66',
        weight: '23 - 41',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/SJyBfg5NX.jpg',
        temperament: 'Alert, Loyal, Obedient, Curious, Confident, Intelligent, Watchful, Courageous',
        createdInDatabase: false
      },
      {
        id: 116,
        name: 'German Shorthaired Pointer',
        height: '53 - 64',
        weight: '20 - 32',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/SJqBMg5Nm.jpg',
        temperament: 'Boisterous, Bold, Affectionate, Intelligent, Cooperative, Trainable',
        createdInDatabase: false
      },
      {
        id: 119,
        name: 'Giant Schnauzer',
        height: '60 - 70',
        weight: '29 - 41',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/H1NIzlcV7.jpg',
        temperament: 'Strong Willed, Kind, Loyal, Intelligent, Dominant, Powerful',
        createdInDatabase: false
      },
      {
        id: 120,
        name: 'Glen of Imaal Terrier',
        height: '32 - 36',
        weight: '15 - 18',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/H1oLMe94m.jpg',
        temperament: 'Spirited, Agile, Loyal, Gentle, Active, Courageous',
        createdInDatabase: false
      },
      {
        id: 121,
        name: 'Golden Retriever',
        height: '55 - 61',
        weight: '25 - 34',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/HJ7Pzg5EQ.jpg',
        temperament: 'Intelligent, Kind, Reliable, Friendly, Trustworthy, Confident',
        createdInDatabase: false
      },
      {
        id: 123,
        name: 'Gordon Setter',
        height: '58 - 69',
        weight: '20 - 36',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/SJ5vzx5NX.jpg',
        temperament: 'Fearless, Alert, Loyal, Confident, Gay, Eager',
        createdInDatabase: false
      },
      {
        id: 124,
        name: 'Great Dane',
        height: '71 - 81',
        weight: '50 - 86',
        life_span: '7 - 10 years',
        image: 'https://cdn2.thedogapi.com/images/B1Edfl9NX.jpg',
        temperament: 'Friendly, Devoted, Reserved, Gentle, Confident, Loving',
        createdInDatabase: false
      },
      {
        id: 125,
        name: 'Great Pyrenees',
        height: '64 - 81',
        weight: '39 - 52',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/B12uzg9V7.png',
        temperament: 'Strong Willed, Fearless, Affectionate, Patient, Gentle, Confident',
        createdInDatabase: false
      },
      {
        id: 127,
        name: 'Greyhound',
        height: '69 - 76',
        weight: '23 - 32',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/ryNYMx94X.jpg',
        temperament: 'Affectionate, Athletic, Gentle, Intelligent, Quiet, Even Tempered',
        createdInDatabase: false
      },
      {
        id: 128,
        name: 'Griffon Bruxellois',
        height: '23 - 28',
        weight: '5',
        life_span: '10 – 15 years',
        image: 'https://cdn2.thedogapi.com/images/ryoYGec4Q.jpg',
        temperament: 'Self-important, Inquisitive, Alert, Companionable, Sensitive, Watchful',
        createdInDatabase: false
      },
      {
        id: 129,
        name: 'Harrier',
        height: '46 - 56',
        weight: '18 - 27',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/B1IcfgqE7.jpg',
        temperament: 'Outgoing, Friendly, Cheerful, Sweet-Tempered, Tolerant, Active',
        createdInDatabase: false
      },
      {
        id: 130,
        name: 'Havanese',
        height: '22 - 29',
        weight: '3 - 6',
        life_span: '14 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/rkXiGl9V7.jpg',
        temperament: 'Affectionate, Responsive, Playful, Companionable, Gentle, Intelligent',
        createdInDatabase: false
      },
      {
        id: 134,
        name: 'Irish Setter',
        height: '61 - 69',
        weight: '16 - 32',
        life_span: '10 - 11 years',
        image: 'https://cdn2.thedogapi.com/images/S1osGeqVm.jpg',
        temperament: 'Affectionate, Energetic, Lively, Independent, Playful, Companionable',
        createdInDatabase: false
      },
      {
        id: 135,
        name: 'Irish Terrier',
        height: '46',
        weight: '11 - 12',
        life_span: '12 - 16 years',
        image: 'https://cdn2.thedogapi.com/images/By-hGecVX.jpg',
        temperament: 'Respectful, Lively, Intelligent, Dominant, Protective, Trainable',
        createdInDatabase: false
      },
      {
        id: 137,
        name: 'Irish Wolfhound',
        height: '76 - 89',
        weight: '48 - 82',
        life_span: '6 - 8 years',
        image: 'https://cdn2.thedogapi.com/images/Hyd2zgcEX.jpg',
        temperament: 'Sweet-Tempered, Loyal, Dignified, Patient, Thoughtful, Generous',
        createdInDatabase: false
      },
      {
        id: 138,
        name: 'Italian Greyhound',
        height: '33 - 38',
        weight: '3 - 7',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/SJAnzg9NX.jpg',
        temperament: 'Mischievous, Affectionate, Agile, Athletic, Companionable, Intelligent',
        createdInDatabase: false
      },
      {
        id: 140,
        name: 'Japanese Chin',
        height: '20 - 28',
        weight: '2 - 4',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/r1H6feqEm.jpg',
        temperament: 'Alert, Loyal, Independent, Intelligent, Loving, Cat-like',
        createdInDatabase: false
      },
      {
        id: 141,
        name: 'Japanese Spitz',
        height: '30 - 38',
        weight: '7 - 9',
        life_span: '10 – 16 years',
        image: 'https://cdn2.thedogapi.com/images/HksaMxqNX.jpg',
        temperament: 'Affectionate, Obedient, Playful, Companionable, Intelligent, Proud',
        createdInDatabase: false
      },
      {
        id: 142,
        name: 'Keeshond',
        height: '43 - 46',
        weight: '16 - 20',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/S1GAGg9Vm.jpg',
        temperament: 'Agile, Obedient, Playful, Quick, Sturdy, Bright',
        createdInDatabase: false
      },
      {
        id: 144,
        name: 'Komondor',
        height: '65 - 70',
        weight: '36 - 45',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/Bko0fl547.jpg',
        temperament: 'Steady, Fearless, Affectionate, Independent, Gentle, Calm',
        createdInDatabase: false
      },
      {
        id: 145,
        name: 'Kooikerhondje',
        height: '36 - 41',
        weight: '9 - 14',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/kOMy84GQE.jpg',
        temperament: 'Benevolent, Agile, Alert, Intelligent, Active, Territorial',
        createdInDatabase: false
      },
      {
        id: 147,
        name: 'Kuvasz',
        height: '66 - 76',
        weight: '32 - 52',
        life_span: '8 - 10 years',
        image: 'https://cdn2.thedogapi.com/images/BykZ7ecVX.jpg',
        temperament: 'Clownish, Loyal, Patient, Independent, Intelligent, Protective',
        createdInDatabase: false
      },
      {
        id: 149,
        name: 'Labrador Retriever',
        height: '55 - 62',
        weight: '25 - 36',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/B1uW7l5VX.jpg',
        temperament: 'Kind, Outgoing, Agile, Gentle, Intelligent, Trusting, Even Tempered',
        createdInDatabase: false
      },
      {
        id: 151,
        name: 'Lagotto Romagnolo',
        height: '41 - 48',
        weight: '11 - 16',
        life_span: '14 - 16 years',
        image: 'https://cdn2.thedogapi.com/images/ryzzmgqE7.jpg',
        temperament: 'Keen, Loyal, Companionable, Loving, Active, Trainable',
        createdInDatabase: false
      },
      {
        id: 153,
        name: 'Lancashire Heeler',
        height: '25 - 30',
        weight: '3 - 6',
        life_span: '12 – 15 years',
        image: 'https://cdn2.thedogapi.com/images/S1RGml5Em.jpg',
        temperament: 'Clever, Friendly, Alert, Intelligent',
        createdInDatabase: false
      },
      {
        id: 155,
        name: 'Leonberger',
        height: '65 - 80',
        weight: '54 - 77',
        life_span: '6 - 8 years',
        image: 'https://cdn2.thedogapi.com/images/ByrmQlqVm.jpg',
        temperament: 'Obedient, Fearless, Loyal, Companionable, Adaptable, Loving',
        createdInDatabase: false
      },
      {
        id: 156,
        name: 'Lhasa Apso',
        height: '25 - 28',
        weight: '5 - 8',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/SJp7Qe5EX.jpg',
        temperament: 'Steady, Fearless, Friendly, Devoted, Assertive, Spirited, Energetic, Lively, Alert, Obedient, Playful, Intelligent',
        createdInDatabase: false
      },
      {
        id: 161,
        name: 'Maltese',
        height: '20 - 25',
        weight: '2 - 3',
        life_span: '15 - 18 years',
        image: 'https://cdn2.thedogapi.com/images/B1SV7gqN7.jpg',
        temperament: 'Playful, Docile, Fearless, Affectionate, Sweet-Tempered, Lively, Responsive, Easygoing, Gentle, Intelligent, Active',
        createdInDatabase: false
      },
      {
        id: 165,
        name: 'Miniature American Shepherd',
        height: '33 - 46',
        weight: '9 - 18',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/BkHHQgcN7.jpg',
        temperament: 'Energetic, Loyal, Intelligent, Trainable',
        createdInDatabase: false
      },
      {
        id: 167,
        name: 'Miniature Pinscher',
        height: '25 - 32',
        weight: '4 - 5',
        life_span: '15 years',
        image: 'https://cdn2.thedogapi.com/images/Hy3H7g94X.jpg',
        temperament: 'Clever, Outgoing, Friendly, Energetic, Responsive, Playful',
        createdInDatabase: false
      },
      {
        id: 168,
        name: 'Miniature Schnauzer',
        height: '30 - 36',
        weight: '5 - 9',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/SJIUQl9NX.jpg',
        temperament: 'Fearless, Friendly, Spirited, Alert, Obedient, Intelligent',
        createdInDatabase: false
      },
      {
        id: 171,
        name: 'Newfoundland',
        height: '66 - 71',
        weight: '45 - 68',
        life_span: '8 - 10 years',
        image: 'https://cdn2.thedogapi.com/images/Sk4DXl54m.jpg',
        temperament: 'Sweet-Tempered, Gentle, Trainable',
        createdInDatabase: false
      },
      {
        id: 172,
        name: 'Norfolk Terrier',
        height: '23 - 25',
        weight: '5 - 5',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/B1ADQg94X.jpg',
        temperament: 'Self-confidence, Fearless, Spirited, Companionable, Happy, Lovable',
        createdInDatabase: false
      },
      {
        id: 176,
        name: 'Norwich Terrier',
        height: '25',
        weight: '5 - 5',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/BkgKXlqE7.jpg',
        temperament: 'Hardy, Affectionate, Energetic, Sensitive, Intelligent',
        createdInDatabase: false
      },
      {
        id: 177,
        name: 'Nova Scotia Duck Tolling Retriever',
        height: '43 - 53',
        weight: '16 - 23',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/SyYtQe5V7.jpg',
        temperament: 'Outgoing, Alert, Patient, Intelligent, Loving',
        createdInDatabase: false
      },
      {
        id: 178,
        name: 'Old English Sheepdog',
        height: '53',
        weight: '27 - 45',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/HkZ57lq4m.jpg',
        temperament: 'Sociable, Bubbly, Playful, Adaptable, Intelligent, Loving',
        createdInDatabase: false
      },
      {
        id: 179,
        name: 'Olde English Bulldogge',
        height: '38 - 48',
        weight: 'NaN',
        life_span: '9 – 14 years',
        image: 'https://cdn2.thedogapi.com/images/B1d5me547.jpg',
        temperament: 'Friendly, Alert, Confident, Loving, Courageous, Strong',
        createdInDatabase: false
      },
      {
        id: 181,
        name: 'Papillon',
        height: '20 - 28',
        weight: '1 - 5',
        life_span: '13 - 17 years',
        image: 'https://cdn2.thedogapi.com/images/SkJj7e547.jpg',
        temperament: 'Hardy, Friendly, Energetic, Alert, Intelligent, Happy',
        createdInDatabase: false
      },
      {
        id: 183,
        name: 'Pekingese',
        height: '15 - 23',
        weight: '6',
        life_span: '14 - 18 years',
        image: 'https://cdn2.thedogapi.com/images/ByIiml9Nm.jpg',
        temperament: 'Opinionated, Good-natured, Stubborn, Affectionate, Aggressive, Intelligent',
        createdInDatabase: false
      },
      {
        id: 184,
        name: 'Pembroke Welsh Corgi',
        height: '25 - 30',
        weight: '11 - 14',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/rJ6iQeqEm.jpg',
        temperament: 'Tenacious, Outgoing, Friendly, Bold, Playful, Protective',
        createdInDatabase: false
      },
      {
        id: 185,
        name: 'Perro de Presa Canario',
        height: '56 - 65',
        weight: '40 - 50',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/S1V3Qeq4X.jpg',
        temperament: 'Strong Willed, Suspicious, Gentle, Dominant, Calm',
        createdInDatabase: false
      },
      {
        id: 188,
        name: 'Pharaoh Hound',
        height: '53 - 64',
        weight: '18 - 27',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/Byz6mgqEQ.jpg',
        temperament: 'Affectionate, Sociable, Playful, Intelligent, Active, Trainable',
        createdInDatabase: false
      },
      {
        id: 189,
        name: 'Plott',
        height: '51 - 64',
        weight: '18 - 27',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/B1i67l5VQ.jpg',
        temperament: 'Bold, Alert, Loyal, Intelligent',
        createdInDatabase: false
      },
      {
        id: 193,
        name: 'Pomeranian',
        height: '20 - 30',
        weight: '1 - 3',
        life_span: '15 years',
        image: 'https://cdn2.thedogapi.com/images/HJd0XecNX.jpg',
        temperament: 'Extroverted, Friendly, Sociable, Playful, Intelligent, Active',
        createdInDatabase: false
      },
      {
        id: 196,
        name: 'Poodle (Miniature)',
        height: '28 - 38',
        weight: '7 - 8',
        life_span: '12 – 15 years',
        image: 'https://cdn2.thedogapi.com/images/Hkxk4ecVX.jpg',
        temperament: 'Loyal, like all Dogs',
        createdInDatabase: false
      },
      {
        id: 197,
        name: 'Poodle (Toy)',
        height: '23 - 28',
        weight: '3 - 4',
        life_span: '18 years',
        image: 'https://cdn2.thedogapi.com/images/rJFJVxc4m.jpg',
        temperament: 'Loyal, like all Dogs',
        createdInDatabase: false
      },
      {
        id: 201,
        name: 'Pug',
        height: '25 - 30',
        weight: '6 - 8',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/HyJvcl9N7.jpg',
        temperament: 'Docile, Clever, Charming, Stubborn, Sociable, Playful, Quiet, Attentive',
        createdInDatabase: false
      },
      {
        id: 204,
        name: 'Puli',
        height: '41 - 43',
        weight: '11 - 16',
        life_span: '12 - 16 Years years',
        image: 'https://cdn2.thedogapi.com/images/ryPgVl5N7.jpg',
        temperament: 'Energetic, Agile, Loyal, Obedient, Intelligent, Faithful',
        createdInDatabase: false
      },
      {
        id: 205,
        name: 'Pumi',
        height: '38 - 47',
        weight: '8 - 15',
        life_span: '13 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/SyRe4xcN7.jpg',
        temperament: 'Lively, Reserved, Intelligent, Active, Protective, Vocal',
        createdInDatabase: false
      },
      {
        id: 207,
        name: 'Rat Terrier',
        height: '25 - 33',
        weight: '4 - 11',
        life_span: '12 - 18 years',
        image: 'https://cdn2.thedogapi.com/images/HkXWNl9E7.jpg',
        temperament: 'Affectionate, Lively, Inquisitive, Alert, Intelligent, Loving',
        createdInDatabase: false
      },
      {
        id: 208,
        name: 'Redbone Coonhound',
        height: '53 - 69',
        weight: '20 - 36',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/HJMzEl5N7.jpg',
        temperament: 'Affectionate, Energetic, Independent, Companionable, Familial, Unflappable',
        createdInDatabase: false
      },
      {
        id: 209,
        name: 'Rhodesian Ridgeback',
        height: '61 - 69',
        weight: '34 - 36',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/By9zNgqE7.jpg',
        temperament: 'Strong Willed, Mischievous, Loyal, Dignified, Sensitive, Intelligent',
        createdInDatabase: false
      },
      {
        id: 210,
        name: 'Rottweiler',
        height: '56 - 69',
        weight: '34 - 50',
        life_span: '8 - 10 years',
        image: 'https://cdn2.thedogapi.com/images/r1xXEgcNX.jpg',
        temperament: 'Steady, Good-natured, Fearless, Devoted, Alert, Obedient, Confident, Self-assured, Calm, Courageous',
        createdInDatabase: false
      },
      {
        id: 211,
        name: 'Russian Toy',
        height: '19 - 27',
        weight: '1 - 3',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/HkP7Vxc4Q.jpg',
        temperament: 'Loyal, like all Dogs',
        createdInDatabase: false
      },
      {
        id: 212,
        name: 'Saint Bernard',
        height: '65 - 70',
        weight: '59 - 82',
        life_span: '7 - 10 years',
        image: 'https://cdn2.thedogapi.com/images/_Qf9nfRzL.png',
        temperament: 'Friendly, Lively, Gentle, Watchful, Calm',
        createdInDatabase: false
      },
      {
        id: 213,
        name: 'Saluki',
        height: '58 - 71',
        weight: '16 - 29',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/fjFIuehNo.jpg',
        temperament: 'Aloof, Reserved, Intelligent, Quiet',
        createdInDatabase: false
      },
      {
        id: 214,
        name: 'Samoyed',
        height: '48 - 60',
        weight: '23 - 27',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/S1T8Ee9Nm.jpg',
        temperament: 'Stubborn, Friendly, Sociable, Lively, Alert, Playful',
        createdInDatabase: false
      },
      {
        id: 216,
        name: 'Schipperke',
        height: '25 - 33',
        weight: '5 - 7',
        life_span: '13 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/SyBvVgc47.jpg',
        temperament: 'Fearless, Agile, Curious, Independent, Confident, Faithful',
        createdInDatabase: false
      },
      {
        id: 218,
        name: 'Scottish Deerhound',
        height: '71 - 81',
        weight: '32 - 59',
        life_span: '8 - 10 years',
        image: 'https://cdn2.thedogapi.com/images/SkNjqx9NQ.jpg',
        temperament: 'Docile, Friendly, Dignified, Gentle',
        createdInDatabase: false
      },
      {
        id: 219,
        name: 'Scottish Terrier',
        height: '25',
        weight: '8 - 10',
        life_span: '11 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/Bklnce5NX.jpg',
        temperament: 'Feisty, Alert, Independent, Playful, Quick, Self-assured',
        createdInDatabase: false
      },
      {
        id: 221,
        name: 'Shetland Sheepdog',
        height: '33 - 41',
        weight: '14',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/rJa29l9E7.jpg',
        temperament: 'Affectionate, Lively, Responsive, Alert, Loyal, Reserved, Playful, Gentle, Intelligent, Active, Trainable, Strong',
        createdInDatabase: false
      },
      {
        id: 222,
        name: 'Shiba Inu',
        height: '34 - 42',
        weight: '8 - 10',
        life_span: '12 - 16 years',
        image: 'https://cdn2.thedogapi.com/images/Zn3IjPX3f.jpg',
        temperament: 'Charming, Fearless, Keen, Alert, Confident, Faithful',
        createdInDatabase: false
      },
      {
        id: 223,
        name: 'Shih Tzu',
        height: '20 - 28',
        weight: '4 - 7',
        life_span: '10 - 18 years',
        image: 'https://cdn2.thedogapi.com/images/BkrJjgcV7.jpg',
        temperament: 'Clever, Spunky, Outgoing, Friendly, Affectionate, Lively, Alert, Loyal, Independent, Playful, Gentle, Intelligent, Happy, Active, Courageous',
        createdInDatabase: false
      },
      {
        id: 225,
        name: 'Shiloh Shepherd',
        height: '66 - 76',
        weight: '54 - 64',
        life_span: '9 – 14 years',
        image: 'https://cdn2.thedogapi.com/images/SJJxjecEX.jpg',
        temperament: 'Outgoing, Loyal, Companionable, Gentle, Loving, Trainable',
        createdInDatabase: false
      },
      {
        id: 226,
        name: 'Siberian Husky',
        height: '51 - 60',
        weight: '16 - 27',
        life_span: '12 years',
        image: 'https://cdn2.thedogapi.com/images/S17ZilqNm.jpg',
        temperament: 'Outgoing, Friendly, Alert, Gentle, Intelligent',
        createdInDatabase: false
      },
      {
        id: 228,
        name: 'Silky Terrier',
        height: '23 - 25',
        weight: '4 - 5',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/ByzGsl5Nm.jpg',
        temperament: 'Friendly, Responsive, Inquisitive, Alert, Quick, Joyful',
        createdInDatabase: false
      },
      {
        id: 232,
        name: 'Smooth Fox Terrier',
        height: '39',
        weight: 'NaN - 8',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/Syszjx9Em.jpg',
        temperament: 'Fearless, Affectionate, Alert, Playful, Intelligent, Active',
        createdInDatabase: false
      },
      {
        id: 233,
        name: 'Soft Coated Wheaten Terrier',
        height: '41 - 46',
        weight: '14 - 18',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/HJHmix5NQ.jpg',
        temperament: 'Affectionate, Spirited, Energetic, Playful, Intelligent, Faithful',
        createdInDatabase: false
      },
      {
        id: 235,
        name: 'Spanish Water Dog',
        height: '41 - 51',
        weight: '14 - 23',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/HJf4jl9VX.jpg',
        temperament: 'Trainable, Diligent, Affectionate, Loyal, Athletic, Intelligent',
        createdInDatabase: false
      },
      {
        id: 236,
        name: 'Spinone Italiano',
        height: '57 - 70',
        weight: '28 - 39',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/rk5Eoe5Nm.jpg',
        temperament: 'Docile, Friendly, Affectionate, Loyal, Patient, Gentle',
        createdInDatabase: false
      },
      {
        id: 238,
        name: 'Staffordshire Bull Terrier',
        height: '36 - 41',
        weight: '11 - 17',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/H1zSie9V7.jpg',
        temperament: 'Reliable, Fearless, Bold, Affectionate, Loyal, Intelligent, Courageous',
        createdInDatabase: false
      },
      {
        id: 239,
        name: 'Standard Schnauzer',
        height: '44 - 50',
        weight: '14 - 23',
        life_span: '13 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/tmzeu6ID_.jpg',
        temperament: 'Trainable, Good-natured, Devoted, Lively, Playful, Intelligent',
        createdInDatabase: false
      },
      {
        id: 242,
        name: 'Swedish Vallhund',
        height: '29 - 34',
        weight: '9 - 14',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/HJ-Dix94Q.jpg',
        temperament: 'Fearless, Friendly, Energetic, Alert, Intelligent, Watchful',
        createdInDatabase: false
      },
      {
        id: 243,
        name: 'Thai Ridgeback',
        height: '51 - 61',
        weight: '16 - 25',
        life_span: '10 - 12 years',
        image: 'https://cdn2.thedogapi.com/images/zv89hR-O8.jpg',
        temperament: 'Protective, Loyal, Independent, Intelligent, Loving, Familial',
        createdInDatabase: false
      },
      {
        id: 244,
        name: 'Tibetan Mastiff',
        height: '61 - 66',
        weight: '39 - 64',
        life_span: '10 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/SkM9sec47.jpg',
        temperament: 'Strong Willed, Tenacious, Aloof, Stubborn, Intelligent, Protective',
        createdInDatabase: false
      },
      {
        id: 245,
        name: 'Tibetan Spaniel',
        height: '25',
        weight: '4 - 7',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/Hyjcol947.jpg',
        temperament: 'Willful, Aloof, Assertive, Independent, Playful, Intelligent, Happy',
        createdInDatabase: false
      },
      {
        id: 246,
        name: 'Tibetan Terrier',
        height: '36 - 43',
        weight: '9 - 11',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/6f5n_42mB.jpg',
        temperament: 'Affectionate, Energetic, Amiable, Reserved, Gentle, Sensitive',
        createdInDatabase: false
      },
      {
        id: 248,
        name: 'Toy Fox Terrier',
        height: '20 - 28',
        weight: '2 - 4',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/B17ase9V7.jpg',
        temperament: 'Friendly, Spirited, Alert, Loyal, Playful, Intelligent',
        createdInDatabase: false
      },
      {
        id: 250,
        name: 'Treeing Walker Coonhound',
        height: '51 - 69',
        weight: '20 - 36',
        life_span: '10 - 13 years',
        image: 'https://cdn2.thedogapi.com/images/SkRpsgc47.jpg',
        temperament: 'Clever, Affectionate, Confident, Intelligent, Loving, Trainable',
        createdInDatabase: false
      },
      {
        id: 251,
        name: 'Vizsla',
        height: '53 - 61',
        weight: '23 - 29',
        life_span: '10 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/r1o0jx9Em.jpg',
        temperament: 'Affectionate, Energetic, Loyal, Gentle, Quiet',
        createdInDatabase: false
      },
      {
        id: 253,
        name: 'Weimaraner',
        height: '58 - 69',
        weight: '25 - 41',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/SyU12l9V7.jpg',
        temperament: 'Steady, Aloof, Stubborn, Energetic, Alert, Intelligent, Powerful, Fast',
        createdInDatabase: false
      },
      {
        id: 254,
        name: 'Welsh Springer Spaniel',
        height: '43 - 48',
        weight: '16 - 25',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/BJ1gnx5Vm.jpg',
        temperament: 'Stubborn, Friendly, Affectionate, Loyal, Playful, Active',
        createdInDatabase: false
      },
      {
        id: 256,
        name: 'West Highland White Terrier',
        height: '25 - 28',
        weight: '7 - 10',
        life_span: '15 - 20 years',
        image: 'https://cdn2.thedogapi.com/images/Bkdx2g5Em.jpg',
        temperament: 'Hardy, Friendly, Alert, Independent, Gay, Active, Courageous',
        createdInDatabase: false
      },
      {
        id: 257,
        name: 'Whippet',
        height: '46 - 56',
        weight: '11 - 16',
        life_span: '12 - 15 years',
        image: 'https://cdn2.thedogapi.com/images/Hyv-ne94m.jpg',
        temperament: 'Friendly, Affectionate, Lively, Gentle, Intelligent, Quiet',
        createdInDatabase: false
      },
      {
        id: 258,
        name: 'White Shepherd',
        height: '56 - 64',
        weight: '27 - 39',
        life_span: '12 – 14 years',
        image: 'https://cdn2.thedogapi.com/images/r14M3e9E7.jpg',
        temperament: 'Self-confidence, Aloof, Fearless, Alert, Companionable, Eager',
        createdInDatabase: false
      },
      {
        id: 259,
        name: 'Wire Fox Terrier',
        height: '33 - 41',
        weight: '7 - 9',
        life_span: '13 – 14 years',
        image: 'https://cdn2.thedogapi.com/images/SJ6f2g9EQ.jpg',
        temperament: 'Fearless, Friendly, Bold, Keen, Alert, Quick',
        createdInDatabase: false
      },
      {
        id: 260,
        name: 'Wirehaired Pointing Griffon',
        height: '51 - 61',
        weight: '20 - 32',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/Bkam2l9Vm.jpg',
        temperament: 'Loyal, Gentle, Vigilant, Trainable, Proud',
        createdInDatabase: false
      },
      {
        id: 261,
        name: 'Wirehaired Vizsla',
        height: '55 - 64',
        weight: '20 - 29',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/r1I4hl5Em.jpg',
        temperament: 'Loyal, like all Dogs',
        createdInDatabase: false
      },
      {
        id: 262,
        name: 'Xoloitzcuintli',
        height: '25 - 58',
        weight: '4 - 14',
        life_span: '12 - 14 years',
        image: 'https://cdn2.thedogapi.com/images/HkNS3gqEm.jpg',
        temperament: 'Cheerful, Alert, Companionable, Intelligent, Protective, Calm',
        createdInDatabase: false
      },
      {
        id: 264,
        name: 'Yorkshire Terrier',
        height: '20 - 23',
        weight: '2 - 3',
        life_span: '12 - 16 years',
        image: 'https://cdn2.thedogapi.com/images/B12BnxcVQ.jpg',
        temperament: 'Bold, Independent, Confident, Intelligent, Courageous',
        createdInDatabase: false
      },
      {
        id: '792bfd0f-0c5b-4792-b8e4-3972581883a9',
        name: 'z_TEST_Perritos que se rascan la patitas',
        height: '1 - 100',
        weight: '1 - 100',
        life_span: '100 years',
        image: 'https://cdn.pixabay.com/photo/2016/02/18/18/37/puppy-1207816_960_720.jpg',
        createdInDatabase: true,
        temperament: 'Active, Loyal'
      }
    ];
 
    export let temperament = [
      'Active',
      'Adaptable',
      'Adventurous',
      'Affectionate',
      'Aggressive',
      'Agile',
      'Alert',
      'Aloof',
      'Amiable',
      'Assertive',
      'Athletic',
      'Attentive',
      'Benevolent',
      'Boisterous',
      'Bold',
      'Bossy',
      'Brave',
      'Bright',
      'Bubbly',
      'Calm',
      'Cat-like',
      'Cautious',
      'Charming',
      'Cheerful',
      'Clever',
      'Clownish',
      'Companionable',
      'Composed',
      'Confident',
      'Cooperative',
      'Courageous',
      'Cunning',
      'Curious',
      'Determined',
      'Devoted',
      'Dignified',
      'Diligent',
      'Docile',
      'Dominant',
      'Dutiful',
      'Eager',
      'Easygoing',
      'Energetic',
      'Even Tempered',
      'Excitable',
      'Extroverted',
      'Faithful',
      'Familial',
      'Fast',
      'Fearless',
      'Feisty',
      'Fierce',
      'Friendly',
      'Fun-loving',
      'Gay',
      'Generous',
      'Gentle',
      'Good-natured',
      'Good-tempered',
      'Great-hearted',
      'Happy',
      'Hard-working',
      'Hardworking',
      'Hardy',
      'Independent',
      'Inquisitive',
      'Intelligent',
      'Joyful',
      'Keen',
      'Kind',
      'Lively',
      'Lovable',
      'Loving',
      'Loyal',
      'Merry',
      'Mischievous',
      'Obedient',
      'Opinionated',
      'Outgoing',
      'Patient',
      'People-Oriented',
      'Playful',
      'Powerful',
      'Protective',
      'Proud',
      'Quick',
      'Quiet',
      'Rational',
      'Receptive',
      'Refined',
      'Reliable',
      'Reserved',
      'Respectful',
      'Responsible',
      'Responsive',
      'Rugged',
      'Self-assured',
      'Self-confidence',
      'Self-important',
      'Sensitive',
      'Sociable',
      'Spirited',
      'Spunky',
      'Stable',
      'Steady',
      'Strong',
      'Strong Willed',
      'Stubborn',
      'Sturdy',
      'Suspicious',
      'Sweet-Tempered',
      'Tenacious',
      'Territorial',
      'Thoughtful',
      'Tolerant',
      'Trainable',
      'Trusting',
      'Trustworthy',
      'Unflappable',
      'Vigilant',
      'Vocal',
      'Watchful',
      'Wild',
      'Willful'
    ];
